import type { Metadata } from 'next';
import Boldonse from 'next/font/local';
import { Funnel_Display } from 'next/font/google';
import './globals.css';
import ReactLenis from 'lenis/react';

const funnelDisplay = Funnel_Display({
  weight: '400',
  variable: '--font-body',
  subsets: ['latin'],
});

const boldonse = Boldonse({
  src: '../../public/fonts/boldonse-regular.ttf',
  variable: '--font-header',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ReactLenis root>
        <body
          className={`${funnelDisplay.variable} ${boldonse.variable} antialiased`}
        >
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
