import type { Metadata } from 'next';
import { Anton, JetBrains_Mono } from 'next/font/google';
import './globals.css';

const bebasNeue = Anton({
  weight: '400',
  variable: '--font-zen-dots',
  subsets: ['latin'],
});

const inter = JetBrains_Mono({
  variable: '--font-lexend',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang='en'>
      <body className={`${bebasNeue.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
